
export const generatePDF = async (content: string, title: string) => {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  // Initial Settings
  doc.setTextColor(30, 41, 59); // Slate 800
  const pageHeight = doc.internal.pageSize.getHeight();
  let cursorY = 20;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(title.toUpperCase(), pageWidth / 2, cursorY, { align: 'center' });
  cursorY += 15;

  const lines = content.split('\n');
  
  for (const line of lines) {
    if (line.trim() === '') {
      cursorY += 5;
      continue;
    }

    // Handle Headers (#)
    if (line.startsWith('#')) {
      const headerText = line.replace(/^[#\s]+/, '');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      
      const wrappedHeader = doc.splitTextToSize(headerText, maxWidth);
      for (const hLine of wrappedHeader) {
        if (cursorY > pageHeight - 30) { doc.addPage(); cursorY = 20; }
        doc.text(hLine, margin, cursorY);
        cursorY += 8;
      }
      cursorY += 4;
      continue;
    }

    // Default Body Text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    // Simple Bold Support (**text**)
    if (line.includes('**')) {
      doc.setFont('helvetica', 'bold');
      const cleanLine = line.replace(/\*\*/g, '');
      const wrapped = doc.splitTextToSize(cleanLine, maxWidth);
      for (const wLine of wrapped) {
        if (cursorY > pageHeight - 30) { doc.addPage(); cursorY = 20; }
        doc.text(wLine, margin, cursorY);
        cursorY += 7;
      }
      continue;
    }

    const wrappedBody = doc.splitTextToSize(line, maxWidth);
    for (const bLine of wrappedBody) {
      if (cursorY > pageHeight - 30) { doc.addPage(); cursorY = 20; }
      doc.text(bLine, margin, cursorY);
      cursorY += 7;
    }
  }

  // Footer
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.line(margin, pageHeight - 25, pageWidth - margin, pageHeight - 25);
  
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const footerNote = `Generated by Statum Legal - ${new Date().toLocaleDateString()}`;
  doc.text(footerNote, margin, pageHeight - 15);

  const blob = doc.output('blob');
  const url = URL.createObjectURL(blob);
  
  // Trigger download
  const link = document.createElement('a');
  link.href = url;
  link.download = `${title.replace(/\s+/g, '_')}.pdf`;
  link.click();
  
  return url;
};

export const generateDOCX = async (content: string, title: string) => {
  const { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } = await import('docx');
  const { saveAs } = await import('file-saver');
  
  const lines = content.split('\n');
  const children = [];

  // Add Title
  children.push(new Paragraph({
    text: title.toUpperCase(),
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }));

  for (const line of lines) {
    if (line.trim() === '') {
      children.push(new Paragraph({ spacing: { after: 100 } }));
      continue;
    }

    const isHeader = line.startsWith('#');
    const isBold = line.includes('**') || /^Clause \d/i.test(line) || /^\d+\.\d+/i.test(line);

    children.push(new Paragraph({
      children: [
        new TextRun({
          text: line.replace(/[#*]/g, '').trim(),
          bold: isBold || isHeader,
          size: isHeader ? 28 : 22,
        }),
      ],
      spacing: { before: isHeader ? 240 : 120, after: 120 },
    }));
  }

  // Footer
  children.push(new Paragraph({ spacing: { before: 400 } }));
  children.push(new Paragraph({
    children: [
      new TextRun({
        text: `Generated by Statum Legal - ${new Date().toLocaleDateString()}`,
        color: "64748b",
        size: 16,
        italics: true,
      }),
    ],
    alignment: AlignmentType.CENTER,
  }));

  const doc = new Document({
    sections: [{
      properties: {},
      children: children,
    }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  saveAs(blob, `${title.replace(/\s+/g, '_')}.docx`);
  return url;
};
